add top package arg to hybrid nix.sh to allow pure import
ref https://garnix.io/blog/converting-to-flakes, as below

It may happen that your existing project doesn't have pkgs as an argument, but instead imports <nixpkgs> directly:

let pkgs = import <nixpkgs>
in ...

In this case, you'll see an error such as:

error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)

To fix this, refactor your code so the pkgs is an argument, and provide the argument from your flake as above. You can have the default value of the pkgs argument be the same:

{ pkgs ? import <nixpkgs> }:
...