override fastapi's pydantic to 1.10.0 to fix promnesia issue #438
https://github.com/karlicoss/promnesia/issues/438

```
AttributeError: 'pydantic_core._pydantic_core.Url' object has no
attribute 'strip'
```

is thrown on every page access.

this is most likely caused by an API breakage between pydantic 1->2;
this commit tricks fastapi into thinking it uses the latest version
of pydantic in the nixpkgs (2.6.3 as of this commit) but pins it to
1.10.16